name: Deploy To-Do App a VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout codigo
        uses: actions/checkout@v6


      - name: Configurar Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'


      - name: Verificar Node y npm
        run: |
          node -v
          npm -v


      - name: Instalar dependencias backend
        working-directory: ./backend
        run: npm install --omit=dev


      - name: Ejecutar pruebas
        working-directory: ./backend
        run: npm test --if-present


      - name: Configurar SSH
        run: |
          mkdir -p ~/.ssh

          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa

          chmod 600 ~/.ssh/id_rsa

          ssh-keyscan -H "${{ secrets.VPS_HOST }}" >> ~/.ssh/known_hosts


      - name: Probar conexion SSH
        run: |
          ssh \
          -i ~/.ssh/id_rsa \
          ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
          "echo Conexion SSH correcta"


      - name: Sincronizar archivos al VPS
        run: |
          rsync -avz \
          --exclude node_modules \
          --exclude .git \
          --exclude .github \
          --exclude .env \
          -e "ssh -i ~/.ssh/id_rsa" \
          ./ \
          ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/todo-app/


      - name: Instalar dependencias y reiniciar API
        run: |

          ssh \
          -i ~/.ssh/id_rsa \
          ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} '

          set -e

          cd /var/www/todo-app/backend

          npm install --omit=dev

          sudo systemctl restart todo-api

          sleep 5

          curl -f http://127.0.0.1:3000/api/health

          '


      - name: Resultado
        if: always()
        run: |
          echo "Estado final: ${{ job.status }}"